InternetAuction.Web/Controllers/AuctionController.cs
using InternetAuction.BLL.Interfaces;
using InternetAuction.BLL.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace InternetAuction.Web.Controllers
{
    public class LotsController : Controller
    {
        private readonly ILotService lotService;

        public LotsController(ILotService lotService)
        {
            this.lotService = lotService;
        }

        public ActionResult Lots()
        {
            var lots = lotService.GetAllActiveLots();
            return View(lots);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var lotModel = new LotModel();
            return View(lotModel);
        }

        [HttpPost]
        public async Task<ActionResult> Create(LotModel model)
        {
            if (ModelState.IsValid)
            {
                var lot = new LotModel
                {
                    SaleType = model.SaleType,
                    SellerId = "1",
                    AuctionDate = DateTime.UtcNow.AddDays(3),
                    Bets = new List<int>(),
                    Car = new CarModel
                    {
                        Brand = model.Car.Brand,
                        Model = model.Car.Model,
                        Year = model.Car.Year,
                        Mileage = model.Car.Mileage,
                        EngineType = model.Car.EngineType,
                        TechnicalPassport = new TechnicalPassportModel
                        {
                            VIN = model.Car.TechnicalPassport.VIN,
                            Transmission = model.Car.TechnicalPassport.Transmission,
                            DriveUnit = model.Car.TechnicalPassport.DriveUnit,
                            BodyType = model.Car.TechnicalPassport.BodyType,
                            HasKeys = model.Car.TechnicalPassport.HasKeys
                        }
                    }
                };

                await lotService.AddAsync(lot);

                return View("Details", model);
            }

            return View(model);
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

InternetAuction.Web/Views/Shared/Forbidden.cshtml
@{
    ViewBag.Title = "Forbidden";
}

<h2 class="font-weight-light">403 - Forbidden</h2>

@Html.ActionLink("Back to main page", "ActiveLots", "Lots", null, htmlAttributes: new { @class = "" })

InternetAuction.Web/Views/Shared/InternalError.cshtml
@{
    ViewBag.Title = "InternalError";
}

<h2 class="font-weight-light">500 - Internal Error</h2>

@Html.ActionLink("Back to main page", "ActiveLots", "Lots", null, htmlAttributes: new { @class = "" })

InternetAuction.Web/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
}

<h2 class="font-weight-light">404 - Not Found</h2>

@Html.ActionLink("Back to main page", "ActiveLots", "Lots", null, htmlAttributes: new { @class = "" })

InternetAuction.Web/Views/Shared/_Layout.cshtml
@using AppRoles = InternetAuction.BLL.Infrastructure.Roles;
﻿@using Microsoft.AspNet.Identity
﻿﻿﻿﻿﻿
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand mr-0 mr-lg-2" href="@Url.Action("ActiveLots", "Lots")">
                    <img src="~/Content/images/logo.png" width="50" height="50" class="d-inline-block" alt="logo">
                    <span class="h4 ml-2 font-weight-lighter" >Car Auction</span>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav">
                        <li class="nav-item">@Html.ActionLink("Auction", "ActiveLots", "Lots", null, htmlAttributes: new { @class = "nav-link" })</li>
                        <li class="nav-item">@Html.ActionLink("Create Lot", "Create", "Lots", null, htmlAttributes: new { @class = "nav-link" })</li>
                        <li class="nav-item">
                            @Html.ActionLink("My sale lots", "SaleLots", "Lots", new { userId = User.Identity.GetUserId() }, 
                                            htmlAttributes: new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("My purchased lots", "PurchasedLots", "Lots", new { userId = User.Identity.GetUserId() },
                                            htmlAttributes: new { @class = "nav-link" })
                        </li>
                        @if (User.IsInRole(AppRoles.Admin))
                        {
                            <li class="nav-item">
                                <div class="dropdown nav-item">
                                    <a class="nav-link" id="adminDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Admin
                                    </a>
                                    <div class="dropdown-menu bg-dark" aria-labelledby="adminDropdown">
                                        @Html.ActionLink("All Lots", "AllLots", "Lots", null, htmlAttributes: new { @class = "nav-link  ml-3" })
                                        @Html.ActionLink("Archive Lots", "ArchiveLots", "Lots", null, htmlAttributes: new { @class = "nav-link  ml-3" })
                                        @Html.ActionLink("Users", "Users", "Account", null, htmlAttributes: new { @class = "nav-link  ml-3" })
                                        @Html.ActionLink("Logs", "Logs", "Logs", null, htmlAttributes: new { @class = "nav-link  ml-3" })
                                    </div>
                                </div>
                            </li>
                        }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </nav>
    </header>

    <div class="container mb-3">

        <div class="row">

            <div class="col-lg-3 mb-2">

                <aside class="container">
                    @RenderSection("sidebar", required: false)
                </aside>

            </div>

            <div class="col-lg-9">
                <main>
                    @RenderBody()
                </main>
            </div>
        </div>

    </div>

    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-1 text-center text-white">Copyright &copy; Car Auction, 2020</p>
            <p class="m-1 text-center text-white">
                Icons made by
                <a href="https://www.flaticon.com/authors/smashicons" title="Smashicons">Smashicons</a>
                from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>
            </p>
            <p class="m-1 text-center text-white">This site uses cookies for a better site experience.</p>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>